server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajendratodkari/springCloudConfigStore
          # username: rajendratodkari
          # password: <mypassword>
          search-paths: 
            - '*service'
          default-label: master


# curl localhost:8191/userservice-dev.json | python3 -m json.tool
# curl localhost:8191/orderservice/dev | python3 -m json.tool
# curl localhost:8191/profileservice/dev | python3 -m json.tool
